# Skills Manager - Database Only
# Run: docker-compose -f docker-compose.db-only.yml up -d

services:
  # SQL Server database
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: skills-manager-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - skills-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourStrong@Passw0rd -Q 'SELECT 1'"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Redis cache (optional - for session storage and caching)
  redis:
    image: redis:7-alpine
    container_name: skills-manager-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - skills-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

# Named volumes for data persistence
volumes:
  sqlserver_data:
    driver: local
  redis_data:
    driver: local

# Custom network
networks:
  skills-network:
    driver: bridge
